import Equipo from "../dominio/equipo.mjs";
import Partido from "../dominio/partido.mjs";
import Sistema from "../dominio/sistema.mjs";

export function insertarEquipos(sis){
    let e = new Equipo("Uruguay", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/uruguay.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Corea", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/coreadelsur.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Portugal", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/portugal.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Ghana", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/ghana.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Brasil", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/brasil.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Serbia", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/serbia.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Suiza", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/suiza.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Camerun", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/camerun.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Belgica", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/belgica.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Canada", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/canada.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Marruecos", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/marruecos.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Croacia", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/croacia.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Espana", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/espana.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("CostaRica", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/costarica.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Alemania", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/alemania.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Japon", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/japon.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Tunez", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/tunez.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Australia", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/australia.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Dinamarca", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/dinamarca.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Francia", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/francia.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Argentina", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/argentina.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("ArabiaSaudita", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/arabiasaudita.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Mexico", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/mexico.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Polonia", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/polonia.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Inglaterra", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/inglaterra.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Iran", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/iran.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("EstadosUnidos", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/estadosunidos.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Gales", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/gales.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Qatar", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/qatar.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Ecuador", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/ecuador.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("Senegal", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/senegal.jpg");
    sis.agregarEquipo(e);
    e = new Equipo("PaisesBajos", "https://paladarnegro.net/escudoteca/selecciones/selecciones/img/paises-bajos.jpg");
    sis.agregarEquipo(e);
}

export function insertarPartidos(sis){ 
    let e = new Partido(1,"Qatar","Ecuador","HOY, 20/11","13:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(2,"Inglaterra","Iran","LUN, 21 nov","10:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(3,"Senegal","PaisesBajos","LUN, 21 nov","13:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(4,"EstadosUnidos","Gales","LUN, 21 nov","16:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(5,"Argentina","ArabiaSaudita","MAR, 22 nov","07:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(6,"Dinamarca","Tunez","MAR, 22 nov","10:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(7,"Mexico","Polonia","MAR, 22 nov","13:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(8,"Francia","Australia","MAR, 22 nov","16:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(9,"Marruecos","Croacia","MIE, 23 nov","07:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(10,"Alemania","Japon","MIE, 23 nov","10:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(11,"Espana","CostaRica","MIE, 23 nov","13:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(12,"Belgica","Canada","MIE, 23 nov","16:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(13,"Suiza","Camerun","JUE, 24 nov","07:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(14,"Uruguay","Corea","JUE, 24 nov","10:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(15,"Portugal","Ghana","JUE, 24 nov","13:00",-1,-1);
    sis.agregarPartido(e);
    e = new Partido(16,"Brasil","Serbia","JUE, 24 nov","16:00",-1,-1);
    sis.agregarPartido(e);
}